#Generated by Fabric Compiler ( version 2022.2-SP6.4 <build 146967> ) at Sat Oct  3 15:09:03 2026

set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG484
compile -top_module board_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
