# ----------------------------------------
# Created on: Sun Sep 13 08:07:39 2026
# Auto generated by Pango
# ----------------------------------------

vlib  work
vmap  work ./work
vmap  usim "D:/modelsim/modelsimm/pango_sim_libraries/usim"
vmap  adc_e2 "D:/modelsim/modelsimm/pango_sim_libraries/adc_e2"
vmap  ddc_e2 "D:/modelsim/modelsimm/pango_sim_libraries/ddc_e2"
vmap  dll_e2 "D:/modelsim/modelsimm/pango_sim_libraries/dll_e2"
vmap  hsstlp_lane "D:/modelsim/modelsimm/pango_sim_libraries/hsstlp_lane"
vmap  hsstlp_pll "D:/modelsim/modelsimm/pango_sim_libraries/hsstlp_pll"
vmap  iolhr_dft "D:/modelsim/modelsimm/pango_sim_libraries/iolhr_dft"
vmap  ipal_e1 "D:/modelsim/modelsimm/pango_sim_libraries/ipal_e1"
vmap  ipal_e2 "D:/modelsim/modelsimm/pango_sim_libraries/ipal_e2"
vmap  iserdes_e2 "D:/modelsim/modelsimm/pango_sim_libraries/iserdes_e2"
vmap  oserdes_e2 "D:/modelsim/modelsimm/pango_sim_libraries/oserdes_e2"
vmap  pciegen2 "D:/modelsim/modelsimm/pango_sim_libraries/pciegen2"
vlog -work work   \
"D:/riscv/RISCV/myriscv/topcpu_instrom.v" \
"D:/riscv/RISCV/ipcore/inst_rom/rtl/ipm2l_rom_v1_8_inst_rom.v" \
"D:/riscv/RISCV/ipcore/inst_rom/rtl/ipm2l_spram_v1_8_inst_rom.v" \
"D:/riscv/RISCV/ipcore/inst_rom/inst_rom.v" \
"D:/riscv/RISCV/ipcore/data_ram/rtl/ipm2l_spram_v1_8_data_ram.v" \
"D:/riscv/RISCV/ipcore/data_ram/data_ram.v" \
"D:/riscv/RISCV/source/tb_topcpu_instrom.v" 

# ----------------------------------------
