./../../example_design/bench/ddr3_tb/ddr3_test_top_tb.v
./../../example_design/bench/mem/ddr3.v
./../../example_design/bench/mem/ddr3_parameters.vh
./../../example_design/rtl/test_ddr.v
./../../example_design/rtl/prbs15_64bit_v1_0.v
./../../example_design/rtl/prbs31_128bit_v1_0.v
./../../example_design/rtl/axi_bist_top_v1_0.v
./../../example_design/rtl/test_main_ctrl_v1_0.v
./../../example_design/rtl/test_rd_ctrl_v1_0.v
./../../example_design/rtl/test_wr_ctrl_v1_0.v
./../../example_design/rtl/uart_rd_lock.v
./../../example_design/rtl/uart_ctrl_32bit/ips2l_clk_gen_32bit.v
./../../example_design/rtl/uart_ctrl_32bit/ips2l_cmd_parser_32bit.v
./../../example_design/rtl/uart_ctrl_32bit/ips2l_seu_rs232_intf.v
./../../example_design/rtl/uart_ctrl_32bit/ips2l_seu_uart_rx.v
./../../example_design/rtl/uart_ctrl_32bit/ips2l_seu_uart_tx.v
./../../example_design/rtl/uart_ctrl_32bit/ips2l_uart_ctrl_32bit.v
./../../example_design/rtl/uart_ctrl_32bit/ips2l_uart_ctrl_top_32bit.v
./../../example_design/rtl/uart_ctrl_32bit/ips2l_ver_ctrl_32bit.v
./../../example_design/rtl/adc/adc.v
./../../example_design/rtl/adc/adc_ctrl.v
./../../sim_lib/ips2l_rst_sync_v1_3.vp
./../../sim_lib/ddrphy/ips2l_ddrphy_wrlvl_v1_0.vp
./../../sim_lib/ddrphy/ddr3_slice_top_v1_10.v
./../../sim_lib/ddrphy/ips2l_ddrphy_wrcal_v1_7.vp
./../../sim_lib/ddrphy/ips2l_ddrphy_wdata_path_adj_v1_10.vp
./../../sim_lib/ddrphy/ips2l_ddrphy_upcal_v1_0.vp
./../../sim_lib/ddrphy/ips2l_ddrphy_training_ctrl_v1_0.vp
./../../sim_lib/ddrphy/ips2l_ddrphy_slice_rddata_align_v1_0.vp
./../../sim_lib/ddrphy/ips2l_ddrphy_reset_ctrl_v1_3.vp
./../../sim_lib/ddrphy/ips2l_ddrphy_rdcal_v1_10.vp
./../../sim_lib/ddrphy/ips2l_ddrphy_main_ctrl_v1_10.vp
./../../sim_lib/ddrphy/ips2l_ddrphy_init_v1_0.vp
./../../sim_lib/ddrphy/ips2l_ddrphy_info_v1_0.vp
./../../sim_lib/ddrphy/ips2l_ddrphy_gatecal_v1_10.vp
./../../sim_lib/ddrphy/ips2l_ddrphy_gate_update_ctrl_v1_3.vp
./../../sim_lib/ddrphy/ips2l_ddrphy_eyecal_v1_5.vp
./../../sim_lib/ddrphy/ips2l_ddrphy_drift_ctrl_v1_0.vp
./../../sim_lib/ddrphy/ips2l_ddrphy_dqsi_rdel_cal_v1_3.vp
./../../sim_lib/ddrphy/ips2l_ddrphy_dqs_rddata_align_v1_10.vp
./../../sim_lib/ddrphy/ips2l_ddrphy_dqs_gate_coarse_cal_v1_0.vp
./../../sim_lib/ddrphy/ips2l_ddrphy_dll_update_ctrl_v1_3.vp
./../../sim_lib/ddrphy/ips2l_ddrphy_dfi_v1_3.vp
./../../sim_lib/ddrphy/ips2l_ddrphy_gpll_phase_v1_0.vp
./../../sim_lib/ddrphy/ips2l_ddrphy_data_slice_wrlvl_v1_10.vp
./../../sim_lib/ddrphy/ips2l_ddrphy_data_slice_wrcal_v1_10.vp
./../../sim_lib/ddrphy/ips2l_ddrphy_data_slice_v1_10.vp
./../../sim_lib/ddrphy/ips2l_ddrphy_data_slice_dqs_gate_cal_v1_10.vp
./../../sim_lib/ddrphy/ips2l_ddrphy_cpd_ctrl_v1_3.vp
./../../sim_lib/ddrphy/ips2l_ddrphy_cpd_lock_v1_0.vp
./../../sim_lib/ddrphy/ips2l_ddrphy_control_path_adj_v1_10.vp
./../../sim_lib/ddrphy/ips2l_ddrphy_calib_top_v1_10.vp
./../../sim_lib/ddrphy/ips2l_ddrphy_calib_mux_v1_0.vp
./../../sim_lib/ddrphy/ips2l_ddrphy_rst_debounce_v1_0.vp
./../../sim_lib/ddrphy/ips2l_ddrphy_rst_clk_phase_adj_v1_0.vp
./../../sim_lib/pll/ips2l_ddrphy_gpll_v1_3.vp
./../../sim_lib/pll/ips2l_ddrphy_ppll_v1_0.vp
./../../sim_lib/mcdq_ctrl/ips2l_mcdq_apb_cross_v1_2.vp
./../../sim_lib/mcdq_ctrl/ips2l_mcdq_calib_delay_v1_2.vp
./../../sim_lib/mcdq_ctrl/ips2l_mcdq_cfg_apb_v1_2.vp
./../../sim_lib/mcdq_ctrl/ips2l_mcdq_dcd_bm_v1_2.vp
./../../sim_lib/mcdq_ctrl/ips2l_mcdq_dcd_rowaddr_v1_2.vp
./../../sim_lib/mcdq_ctrl/ips2l_mcdq_dcd_sm_v1_2.vp
./../../sim_lib/mcdq_ctrl/ips2l_mcdq_dcd_top_v1_2.vp
./../../sim_lib/mcdq_ctrl/ips2l_mcdq_dcp_back_ctrl_v1_2.vp
./../../sim_lib/mcdq_ctrl/ips2l_mcdq_dcp_buf_v1_2.vp
./../../sim_lib/mcdq_ctrl/ips2l_mcdq_dcp_out_v1_2.vp
./../../sim_lib/mcdq_ctrl/ips2l_mcdq_dcp_top_v1_2.vp
./../../sim_lib/mcdq_ctrl/ips2l_mcdq_dfi_v1_2.vp
./../../sim_lib/mcdq_ctrl/ips2l_mcdq_lp_v1_2.vp
./../../sim_lib/mcdq_ctrl/ips2l_mcdq_mrs_v1_2.vp
./../../sim_lib/mcdq_ctrl/ips2l_mcdq_prefetch_fifo_v1_2.vp
./../../sim_lib/mcdq_ctrl/ips2l_mcdq_rdatapath_v1_2.vp
./../../sim_lib/mcdq_ctrl/ips2l_mcdq_reg_fifo2_v1_2.vp
./../../sim_lib/mcdq_ctrl/ips2l_mcdq_ui_axi_v1_2a.vp
./../../sim_lib/mcdq_ctrl/ips2l_mcdq_wdatapath_v1_2.vp
./../../sim_lib/mcdq_ctrl/ips2l_mcdq_wdp_align_v1_2.vp
./../../sim_lib/mcdq_ctrl/ips2l_mcdq_wdp_dcp_v1_2.vp
./../../sim_lib/mcdq_ctrl/ips2l_mcdq_wrapper_v1_2b.vp
./../../sim_lib/mcdq_ctrl/syn_mod/ips2l_mcdq_com_timing_v1_2.vp
./../../sim_lib/mcdq_ctrl/syn_mod/ips2l_mcdq_tfaw_timing_v1_2.vp
./../../sim_lib/mcdq_ctrl/syn_mod/ips2l_mcdq_tfaw_v1_2.vp
./../../sim_lib/mcdq_ctrl/syn_mod/ips2l_mcdq_timing_act2wr_pass_v1_2.vp
./../../sim_lib/mcdq_ctrl/syn_mod/ips2l_mcdq_timing_act_pass_v1_2.vp
./../../sim_lib/mcdq_ctrl/syn_mod/ips2l_mcdq_timing_pre_pass_v1_2.vp
./../../sim_lib/mcdq_ctrl/syn_mod/ips2l_mcdq_timing_rd_pass_v1_2.vp
./../../sim_lib/mcdq_ctrl/syn_mod/ips2l_mcdq_timing_ref_pass_v1_2.vp
./../../sim_lib/mcdq_ctrl/syn_mod/ips2l_mcdq_timing_wr_pass_v1_2.vp
./../../sim_lib/mcdq_ctrl/syn_mod/ips2l_mcdq_trc_timing_v1_2.vp
./../../sim_lib/mcdq_ctrl/distributed_fifo/ips2l_distributed_fifo_v1_0.vp
./../../sim_lib/mcdq_ctrl/distributed_fifo/rtl/ips2l_distributed_fifo_ctr_v1_0.vp
./../../sim_lib/mcdq_ctrl/distributed_fifo/rtl/ips2l_distributed_fifo_v1_0_distributed_fifo_v1_0.vp
./../../sim_lib/mcdq_ctrl/distributed_fifo/rtl/ips2l_distributed_sdpram_v1_0_distributed_fifo_v1_0.vp
C:/pango/PDS_2022.2-SP6.4/ip/system_ip/ips2l_hmic_s/ips2l_hmic_eval/ips2l_hmic_s/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/dll_e2_source_codes/dll_e2_dly_chain.vp
C:/pango/PDS_2022.2-SP6.4/ip/system_ip/ips2l_hmic_s/ips2l_hmic_eval/ips2l_hmic_s/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/dll_e2_source_codes/dll_e2_ddrphy_dll_fdiv.vp
C:/pango/PDS_2022.2-SP6.4/ip/system_ip/ips2l_hmic_s/ips2l_hmic_eval/ips2l_hmic_s/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/dll_e2_source_codes/dll_e2_ddrphy_dll_fsm.vp
C:/pango/PDS_2022.2-SP6.4/ip/system_ip/ips2l_hmic_s/ips2l_hmic_eval/ips2l_hmic_s/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/dll_e2_source_codes/dll_e2_dll_dff.vp
C:/pango/PDS_2022.2-SP6.4/ip/system_ip/ips2l_hmic_s/ips2l_hmic_eval/ips2l_hmic_s/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/dll_e2_source_codes/dll_e2_dll_clk_gate.vp
C:/pango/PDS_2022.2-SP6.4/ip/system_ip/ips2l_hmic_s/ips2l_hmic_eval/ips2l_hmic_s/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/dll_e2_source_codes/dll_e2_clk_mux_2to1.vp
C:/pango/PDS_2022.2-SP6.4/ip/system_ip/ips2l_hmic_s/ips2l_hmic_eval/ips2l_hmic_s/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/common_lib/logos2_lib.vp
C:/pango/PDS_2022.2-SP6.4/ip/system_ip/ips2l_hmic_s/ips2l_hmic_eval/ips2l_hmic_s/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/common_lib/logos2_primitive.vp
C:/pango/PDS_2022.2-SP6.4/ip/system_ip/ips2l_hmic_s/ips2l_hmic_eval/ips2l_hmic_s/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/oserdes_e2_source_codes/oserdes_e2_iolhr_ol_gear.vp
C:/pango/PDS_2022.2-SP6.4/ip/system_ip/ips2l_hmic_s/ips2l_hmic_eval/ips2l_hmic_s/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/oserdes_e2_source_codes/oserdes_e2_iolhr_ol_gear_part0.vp
C:/pango/PDS_2022.2-SP6.4/ip/system_ip/ips2l_hmic_s/ips2l_hmic_eval/ips2l_hmic_s/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/oserdes_e2_source_codes/oserdes_e2_iolhr_ol_clkgen.vp
C:/pango/PDS_2022.2-SP6.4/ip/system_ip/ips2l_hmic_s/ips2l_hmic_eval/ips2l_hmic_s/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/oserdes_e2_source_codes/oserdes_e2_iolhr_ol_gearctrl.vp
C:/pango/PDS_2022.2-SP6.4/ip/system_ip/ips2l_hmic_s/ips2l_hmic_eval/ips2l_hmic_s/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/oserdes_e2_source_codes/oserdes_e2_iolhr_ol_srce.vp
C:/pango/PDS_2022.2-SP6.4/ip/system_ip/ips2l_hmic_s/ips2l_hmic_eval/ips2l_hmic_s/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/oserdes_e2_source_codes/oserdes_e2_iolhr_ol_odlygray2therm.vp
C:/pango/PDS_2022.2-SP6.4/ip/system_ip/ips2l_hmic_s/ips2l_hmic_eval/ips2l_hmic_s/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/oserdes_e2_source_codes/oserdes_e2_iolhr_ol_tgear.vp
C:/pango/PDS_2022.2-SP6.4/ip/system_ip/ips2l_hmic_s/ips2l_hmic_eval/ips2l_hmic_s/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/oserdes_e2_source_codes/oserdes_e2_iolhr_ol_tgear_part0.vp
C:/pango/PDS_2022.2-SP6.4/ip/system_ip/ips2l_hmic_s/ips2l_hmic_eval/ips2l_hmic_s/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/oserdes_e2_source_codes/oserdes_e2_iolhr_ol.vp
C:/pango/PDS_2022.2-SP6.4/ip/system_ip/ips2l_hmic_s/ips2l_hmic_eval/ips2l_hmic_s/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/iserdes_e2_source_codes/iserdes_e2_iolhr_il_data.vp
C:/pango/PDS_2022.2-SP6.4/ip/system_ip/ips2l_hmic_s/ips2l_hmic_eval/ips2l_hmic_s/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/iserdes_e2_source_codes/iserdes_e2_iolhr_il_gear.vp
C:/pango/PDS_2022.2-SP6.4/ip/system_ip/ips2l_hmic_s/ips2l_hmic_eval/ips2l_hmic_s/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/iserdes_e2_source_codes/iserdes_e2_iolhr_il_clkgen.vp
C:/pango/PDS_2022.2-SP6.4/ip/system_ip/ips2l_hmic_s/ips2l_hmic_eval/ips2l_hmic_s/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/iserdes_e2_source_codes/iserdes_e2_iolhr_il_gearctrl.vp
C:/pango/PDS_2022.2-SP6.4/ip/system_ip/ips2l_hmic_s/ips2l_hmic_eval/ips2l_hmic_s/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/iserdes_e2_source_codes/iserdes_e2_iolhr_il_srce.vp
C:/pango/PDS_2022.2-SP6.4/ip/system_ip/ips2l_hmic_s/ips2l_hmic_eval/ips2l_hmic_s/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddc_e2_source_codes/ddc_e2_ddrphy_gray2therm.vp
C:/pango/PDS_2022.2-SP6.4/ip/system_ip/ips2l_hmic_s/ips2l_hmic_eval/ips2l_hmic_s/../../../../../arch/vendor/pango/verilog/simulation/modelsim10.2c/ddc_e2_source_codes/ddc_e2_dly_chain.vp
./../../ddr3.v
./../../ddr3_ddrphy_top.v
 
+define+IPS_DDR_SPEEDUP_SIM  
+define+RTL_SIM 
+define+den4096Mb   
+define+x16         
+define+sg25E       
